print("Welcome to Intergalactic Mad Libs! Vol. 1.")
print("Let's begin.")

a = str(input("Place: "))
b = str(input("Electronic Device: "))
c = str(input("Male Name: "))
d = str(input("Number: "))
e = str(input("Dance Move: "))
f = str(input("Verb + ing: "))
g = str(input("Vehicle: "))
h = str(input("Liquid: "))
i = str(input("Noun: "))
j = str(input("Item: "))
k = str(input("Hiding Place: "))
l = str(input("City: "))
m = str(input("Occupation: "))
n = str(input("Verb + ing: "))
o = str(input("Verb + ing: "))
p = str(input("Plural Noun: "))
q = str(input("Something Terrifying: "))
r = str(input("Weather Condition + ing: "))
s = str(input("Adverb: "))
t = str(input("Monster: "))
u = str(input("Verb: "))
v = str(input("Adverb: "))
w = str(input("Plant + s: "))
x = str(input("Exclamation: "))
y = str(input("Building: "))
z = str(input("Adverb: "))
aa = str(input("Body Part: "))
bb = str(input("Expletive: "))
cc = str(input("Appliance: "))
dd = str(input("Destructive Verb + ing: "))
ee = str(input("Adjective: "))
ff = str(input("Verb + ing: "))
gg = str(input("Room: "))
hh = str(input("Verb + ing: "))
ii = str(input("Weapon: "))
jj = str(input("Verb + ing: "))
kk = str(input("Murder Verb + ing: "))
ll = str(input("Verb + ing: "))
mm = str(input("Body Part: "))
nn = str(input("Verb: "))
oo = str(input("Adjective: "))
pp = str(input("Weapon: "))
qq = str(input("Ability (Verb): "))
rr = str(input("Combat Move: "))
ss = str(input("Adjective: "))
tt = str(input("Day of The Week: "))
uu = str(input("Verb + s: "))
vv = str(input("Verb: "))
ww = str(input("Body Part: "))
xx = str(input("Important Body Part: "))
yy = str(input("Murder Verb + ed: "))
zz = str(input("Adjective: "))
aaa = str(input("Verb: "))

print()
print("You're walking in " + a + ".")
print("There's no one around.")
print("And your " + b + " is dead.")
print("Out of the corner of your eye, you spot him.")
print(c + ".")
print()
print("He's following you.")
print("About " + d + " feet back.")
print("He " + e + "s and breaks into a sprint.")
print("He's " + f + " on you!")
print(c + ".")
print()
print("You're looking for your " + g + ",")
print("but you're all turned around.")
print("He's almost upon you now")
print("And you can see there's " + h + " on his face!")
print("My God, there's " + h + " everywhere!")
print()
print("Running for your " + i + ",")
print("From " + c + ".")
print("He's brandishing a " + j + ".")
print("It's " + c + ".")
print("Lurking in " + k + ".")
print(l + " " + m + " " + c + ".")
print("Living in " + a + ".")
print(c + ".")
print(n + " for sport.")
print(o + " all the " + p + ".")
print("Actual " + q + " " + c + ".")
print()
print("Now it's " + r + " and you seem to have lost him,")
print("But you're " + s + " lost yourself.")
print("Stranded with a " + t + ",")
print("You " + u + " " + v + " through the " + w + ".")
print(x + "! In the distance,")
print("A small " + y + " with a light on.")
print("Hope!")
print("You move " + z + " toward it,")
print("But your " + aa + "! " + bb + "! " + "It's caught in a " + cc + "!")
print()
print(dd + " your " + aa + ",")
print(ee + ", " + ee + ".")
print(ff + " toward the " + y + ".")
print("Now you're in the " + gg + ".")
print("Sitting inside, " + c + ".")
print(hh + " his " + ii + ",")
print(c + ".")
print("But he doesn't hear you enter.")
print(c + ".")
print("You're " + jj + " up behind him.")
print(kk + " " + q + " " + c + ".")
print(ll + " for your life with " + c + ",")
print("Wrestling the " + ii + " from " + c + ".")
print("Stab it in his " + mm + ".")
print("Safe at last from " + c + ".")
print()
print("You " + nn + " into the " + oo + " " + a + ".")
print("Blood oozing from your " + aa + ".")
print("But you have won.")
print("You have beaten " + c + ".")
print()
print("Wait! He isn't dead! " + c + " Surprise!")
print("There's a " + pp + " to your head, and death in his eyes.")
print("But you can " + qq + ".")
print(rr + " " + m + " " + c + ".")
print(ss + " fight with " + c + ".")
print("Normal " + tt + " night for " + c + ".")
print("You try to swing the " + ii + " at " + c + ".")
print("But blood is draining fast from your stump " + aa + ".")
print()
print("He's dodging every swipe, he " + uu + " to the left,")
print("You " + vv + " to the right, you catch him in the " + ww + ".")
print("You're chopping off his " + xx + " now.")
print("You have just " + yy + " " + c + ".")
print()
print("His " + xx + " topples to the floor, " + zz + ".")
print("You fall to your knees and " + aaa + ".")
print("You're finally safe from " + c + ".")
